server:
  port: 7000
spring:
  application:
    name: service-courier
    #Redis配置
  redis:
    database: 1
    host: ubuntu16.roothk.top
    port: 6379
    password:
#    jedis:
#      pool:
#        ## 连接池最大连接数（使用负值表示没有限制）
#        max-active: 8
#        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms
#        ## 连接池中的最大空闲连接
#        max-idle: 8
#        ## 连接池中的最小空闲连接
#        min-idle: 0
#    ## 连接超时时间（毫秒）
#    timeout: 0ms
eureka:
  client:
    serviceUrl:
      defaultZone: http://ubuntu16.roothk.top:1000/eureka/

#roothk:
#  eid: 1338587
#  key: fe843159-ae88-4d02-bf15-24ab35249249

#http://api.kuaidi100.com/api?id=3bef603438b72b63&com=wanxiangwuliu&nu=604018966088750