#负载均衡-服务消费者Feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://ubuntu16.roothk.top:1000/eureka/
server:
  port: 2000
spring:
  application:
    name: service-images
  #Redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password: aaabbb123456