server:
  port: 9000
spring:
  application:
    name: service-qrcode
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
#      defaultZone: http://aliyun.roothk.top:1000/eureka/