server:
  port: 3000

#service discovery url
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

#datasource config
spring:
  application:
    name: service-calculation
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.84.54:3066/cloud?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8&useSSL=true
    username: root
    password: judeli123!@#

#mybatis config
mybatis:
  typeAliasesPackage: top.roothk.servicecalculation.Service.Model