server:
  port: 3000

#service discovery url
eureka:
  client:
    serviceUrl:
      defaultZone: http://aliyun.roothk.com:1000/eureka/

#datasource config
spring:
  application:
    name: service-calculation
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${mysql.ip}:${mysql.port}/${mysql.database}?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8&useSSL=true
    username: ${mysql.username}
    password: ${mysql.password}

#mybatis config
mybatis:
  typeAliasesPackage: top.roothk.servicecalculation.Service.Model